/*
 * Copyright (c) 2020. Wuklab. All rights reserved.
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <stdint.h>
#include <getopt.h>
#include <uapi/err.h>
#include <uapi/list.h>
#include <uapi/vregion.h>
#include <uapi/hashtable.h>
#include <uapi/bitops.h>
#include <uapi/sched.h>
#include <uapi/thpool.h>
#include <uapi/opcode.h>
#include <uapi/net_header.h>
#include <uapi/profile_point.h>

#include "core.h"

/*
 * This is automatically generated by linker.
 * Oddly, unlike the kernel building with customized linker script,
 * here we need to use pointer of pointer to get the address.
 */
extern struct profile_point *__start_profile_point, *__stop_profile_point;

DEFINE_PROFILE_POINT(unused);

/*
 * TODO
 */
static inline unsigned long cycle2ns(unsigned long cycles)
{
	return cycles / 1;
}

void print_profile_point(struct profile_point *pp)
{
	struct timespec ts = {0, 0};
	unsigned long nr = 0, avg_ns = 0, time_ns = 0;

	nr = pp->nr;
	if (nr == 0)
		return;

	time_ns  = cycle2ns(pp->time_cycles);
	ts.tv_sec = time_ns / NSEC_PER_SEC;
	ts.tv_nsec = time_ns % NSEC_PER_SEC;

	avg_ns = DIV_ROUND_UP(time_ns, nr);

	printf("%s  %35s  %6ld.%09ld  %16ld  %16ld\n",
		pp->enabled? "     on" : "    off",
		pp->pp_name,
		(long)ts.tv_sec, (long)ts.tv_nsec,
		nr,
		avg_ns);
}

void print_profile_points(void)
{
	struct profile_point *pp;
	int count = 0;

	printf("\n");
	printf("LegoMem Profile Points\n");
	printf(" Status                                 Name     Total(cycles)                NR       Avg(cycles)\n");
	//printf(" Status                                 Name          Total(s)                NR           Avg(ns)\n");
	printf("-------  -----------------------------------  ----------------  ----------------  ----------------\n");
	for (pp = (struct profile_point *)&__start_profile_point;
	     pp < (struct profile_point *)&__stop_profile_point; pp++) {
		print_profile_point(pp);
		count++;
	}
	printf("-------  -----------------------------------  ----------------  ----------------  ----------------\n");
	printf("\n");
}
