# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/design_1_vcu_ddr4_controller_0_0.xci
# IP: The module: 'design_1_vcu_ddr4_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/vcu_ddr4_controller_v1_0_1_ddr4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0 || ORIG_REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/ip_0/vcu_ddr4_controller_v1_0_1_ddr4_0_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0_microblaze_mcs || ORIG_REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/bd_eef4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4 || ORIG_REF_NAME==bd_eef4} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/bd_eef4_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_microblaze_I_0 || ORIG_REF_NAME==bd_eef4_microblaze_I_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_1/bd_eef4_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_rst_0_0 || ORIG_REF_NAME==bd_eef4_rst_0_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_2/bd_eef4_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_ilmb_0 || ORIG_REF_NAME==bd_eef4_ilmb_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_3/bd_eef4_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_dlmb_0 || ORIG_REF_NAME==bd_eef4_dlmb_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_4/bd_eef4_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_dlmb_cntlr_0 || ORIG_REF_NAME==bd_eef4_dlmb_cntlr_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_5/bd_eef4_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_ilmb_cntlr_0 || ORIG_REF_NAME==bd_eef4_ilmb_cntlr_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_6/bd_eef4_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_lmb_bram_I_0 || ORIG_REF_NAME==bd_eef4_lmb_bram_I_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_7/bd_eef4_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_eef4_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_8/bd_eef4_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_eef4_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_9/bd_eef4_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_eef4_second_lmb_bram_I_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_10/bd_eef4_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_iomodule_0_0 || ORIG_REF_NAME==bd_eef4_iomodule_0_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/ip_1/vcu_ddr4_controller_v1_0_1_ddr4_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0_phy || ORIG_REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0_phy} -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/bd_eef4_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_microblaze_I_0 || ORIG_REF_NAME==bd_eef4_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/bd_eef4_microblaze_I_0_ooc_debug.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_1/bd_eef4_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_rst_0_0 || ORIG_REF_NAME==bd_eef4_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_1/bd_eef4_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_rst_0_0 || ORIG_REF_NAME==bd_eef4_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_2/bd_eef4_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_ilmb_0 || ORIG_REF_NAME==bd_eef4_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_3/bd_eef4_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_dlmb_0 || ORIG_REF_NAME==bd_eef4_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_6/bd_eef4_lmb_bram_I_0_ooc.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_9/bd_eef4_second_lmb_bram_I_0_ooc.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_10/bd_eef4_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_iomodule_0_0 || ORIG_REF_NAME==bd_eef4_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/bd_eef4_ooc.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/ip_1/par/vcu_ddr4_controller_v1_0_1_ddr4_0_phy_ooc.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/par/vcu_ddr4_controller_v1_0_1_ddr4_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0 || ORIG_REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/constraints/ba317_ddr4_controller.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_vcu_ddr4_controller_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/design_1_vcu_ddr4_controller_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_vcu_ddr4_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/design_1_vcu_ddr4_controller_0_0.xci
# IP: The module: 'design_1_vcu_ddr4_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/vcu_ddr4_controller_v1_0_1_ddr4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0 || ORIG_REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/ip_0/vcu_ddr4_controller_v1_0_1_ddr4_0_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0_microblaze_mcs || ORIG_REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/bd_eef4.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4 || ORIG_REF_NAME==bd_eef4} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/bd_eef4_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_microblaze_I_0 || ORIG_REF_NAME==bd_eef4_microblaze_I_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_1/bd_eef4_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_rst_0_0 || ORIG_REF_NAME==bd_eef4_rst_0_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_2/bd_eef4_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_ilmb_0 || ORIG_REF_NAME==bd_eef4_ilmb_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_3/bd_eef4_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_dlmb_0 || ORIG_REF_NAME==bd_eef4_dlmb_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_4/bd_eef4_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_dlmb_cntlr_0 || ORIG_REF_NAME==bd_eef4_dlmb_cntlr_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_5/bd_eef4_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_ilmb_cntlr_0 || ORIG_REF_NAME==bd_eef4_ilmb_cntlr_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_6/bd_eef4_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_lmb_bram_I_0 || ORIG_REF_NAME==bd_eef4_lmb_bram_I_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_7/bd_eef4_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_eef4_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_8/bd_eef4_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_eef4_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_9/bd_eef4_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_eef4_second_lmb_bram_I_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_10/bd_eef4_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_eef4_iomodule_0_0 || ORIG_REF_NAME==bd_eef4_iomodule_0_0} -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/ip_1/vcu_ddr4_controller_v1_0_1_ddr4_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0_phy || ORIG_REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0_phy} -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/bd_eef4_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_microblaze_I_0 || ORIG_REF_NAME==bd_eef4_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/bd_eef4_microblaze_I_0_ooc_debug.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_1/bd_eef4_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_rst_0_0 || ORIG_REF_NAME==bd_eef4_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_1/bd_eef4_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_rst_0_0 || ORIG_REF_NAME==bd_eef4_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_2/bd_eef4_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_ilmb_0 || ORIG_REF_NAME==bd_eef4_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_3/bd_eef4_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_dlmb_0 || ORIG_REF_NAME==bd_eef4_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_6/bd_eef4_lmb_bram_I_0_ooc.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_9/bd_eef4_second_lmb_bram_I_0_ooc.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_10/bd_eef4_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_eef4_iomodule_0_0 || ORIG_REF_NAME==bd_eef4_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/bd_eef4_ooc.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/ip_1/par/vcu_ddr4_controller_v1_0_1_ddr4_0_phy_ooc.xdc

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/par/vcu_ddr4_controller_v1_0_1_ddr4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0 || ORIG_REF_NAME==vcu_ddr4_controller_v1_0_1_ddr4_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/constraints/ba317_ddr4_controller.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_vcu_ddr4_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/design_1_vcu_ddr4_controller_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_vcu_ddr4_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
