# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /tmp/tmp.uj6Pgihdhk/temp/project_1.cache/wt [current_project]
set_property parent.project_path /tmp/tmp.uj6Pgihdhk/temp/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.4 [current_project]
set_property ip_repo_paths /tmp/tmp.uj6Pgihdhk/ip [current_project]
update_ip_catalog
set_property ip_output_repo /tmp/tmp.uj6Pgihdhk/temp/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_4/design_1_xbar_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_0_0/constraints/vcu.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_0_0/design_1_vcu_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/bd_eef4_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/bd_eef4_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_1/bd_eef4_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_1/bd_eef4_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_2/bd_eef4_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_3/bd_eef4_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_6/bd_eef4_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_9/bd_eef4_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_10/bd_eef4_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/bd_eef4_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/ip_1/par/vcu_ddr4_controller_v1_0_1_ddr4_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/par/vcu_ddr4_controller_v1_0_1_ddr4_0.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/constraints/ba317_ddr4_controller.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/design_1_vcu_ddr4_controller_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_8/design_1_s00_regslice_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_8/design_1_s00_regslice_8_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_9/design_1_s00_regslice_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_9/design_1_s00_regslice_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m01_regslice_2/design_1_m01_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m01_regslice_2/design_1_m01_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_10/design_1_s00_regslice_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_10/design_1_s00_regslice_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_5/design_1_m00_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_5/design_1_m00_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_mmu_0/design_1_s00_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_11/design_1_s00_regslice_11_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_11/design_1_s00_regslice_11_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_0/design_1_auto_rs_w_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_rs_w_0/design_1_auto_rs_w_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_6/design_1_m00_regslice_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_6/design_1_m00_regslice_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_12/design_1_s00_regslice_12_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_12/design_1_s00_regslice_12_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_13/design_1_s00_regslice_13_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_13/design_1_s00_regslice_13_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_7/design_1_m00_regslice_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_7/design_1_m00_regslice_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m01_regslice_3/design_1_m01_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m01_regslice_3/design_1_m01_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_14/design_1_s00_regslice_14_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_14/design_1_s00_regslice_14_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_15/design_1_s00_regslice_15_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_regslice_15/design_1_s00_regslice_15_ooc.xdc]
set_property used_in_synthesis false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/ip_0/sw/calibration_0/Debug/calibration_ddr.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/constrs_1/imports/xdc/vcu_uc2_pll.xdc
set_property used_in_implementation false [get_files /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/constrs_1/imports/xdc/vcu_uc2_pll.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
