# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/vcu_uc2_pll.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_1_0/design_1_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_1_0 || ORIG_REF_NAME==design_1_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_2_0/design_1_axi_interconnect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_2_0 || ORIG_REF_NAME==design_1_axi_interconnect_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_3_0/design_1_axi_interconnect_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_3_0 || ORIG_REF_NAME==design_1_axi_interconnect_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_5_0/design_1_axi_interconnect_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_5_0 || ORIG_REF_NAME==design_1_axi_interconnect_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_6_0/design_1_axi_interconnect_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_6_0 || ORIG_REF_NAME==design_1_axi_interconnect_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_7_0/design_1_axi_interconnect_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_7_0 || ORIG_REF_NAME==design_1_axi_interconnect_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_interrupts_0/design_1_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_interrupts_0 || ORIG_REF_NAME==design_1_interrupts_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_4/design_1_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_4 || ORIG_REF_NAME==design_1_xbar_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_8/design_1_axi_interconnect_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_8 || ORIG_REF_NAME==design_1_axi_interconnect_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_2_1/design_1_axi_interconnect_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_2_1 || ORIG_REF_NAME==design_1_axi_interconnect_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_0/design_1_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_0 || ORIG_REF_NAME==design_1_xlslice_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_2_0 || ORIG_REF_NAME==design_1_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_rd_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_rd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_wr_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_wr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vcu_0_0/design_1_vcu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vcu_0_0 || ORIG_REF_NAME==design_1_vcu_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vcu_ddr4_controller_0_0/design_1_vcu_ddr4_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vcu_ddr4_controller_0_0 || ORIG_REF_NAME==design_1_vcu_ddr4_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_8/design_1_s00_regslice_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_8 || ORIG_REF_NAME==design_1_s00_regslice_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_9/design_1_s00_regslice_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_9 || ORIG_REF_NAME==design_1_s00_regslice_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_4 || ORIG_REF_NAME==design_1_m00_regslice_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m01_regslice_2/design_1_m01_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m01_regslice_2 || ORIG_REF_NAME==design_1_m01_regslice_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_10/design_1_s00_regslice_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_10 || ORIG_REF_NAME==design_1_s00_regslice_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s01_regslice_0 || ORIG_REF_NAME==design_1_s01_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_5/design_1_m00_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_5 || ORIG_REF_NAME==design_1_m00_regslice_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_mmu_0/design_1_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_mmu_0 || ORIG_REF_NAME==design_1_s00_mmu_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_11/design_1_s00_regslice_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_11 || ORIG_REF_NAME==design_1_s00_regslice_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_rs_w_0/design_1_auto_rs_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_0 || ORIG_REF_NAME==design_1_auto_rs_w_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_6/design_1_m00_regslice_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_6 || ORIG_REF_NAME==design_1_m00_regslice_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_12/design_1_s00_regslice_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_12 || ORIG_REF_NAME==design_1_s00_regslice_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_13/design_1_s00_regslice_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_13 || ORIG_REF_NAME==design_1_s00_regslice_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_7/design_1_m00_regslice_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_7 || ORIG_REF_NAME==design_1_m00_regslice_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m01_regslice_3/design_1_m01_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m01_regslice_3 || ORIG_REF_NAME==design_1_m01_regslice_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_14/design_1_s00_regslice_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_14 || ORIG_REF_NAME==design_1_s00_regslice_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_4 || ORIG_REF_NAME==design_1_auto_cc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_5 || ORIG_REF_NAME==design_1_auto_cc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_15/design_1_s00_regslice_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_15 || ORIG_REF_NAME==design_1_s00_regslice_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_6/design_1_auto_cc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_6 || ORIG_REF_NAME==design_1_auto_cc_6} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
