# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4.xci
# IP: The module: 'design_1_m00_regslice_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_m00_regslice_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_m00_regslice_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4.xci
# IP: The module: 'design_1_m00_regslice_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_m00_regslice_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /tmp/tmp.uj6Pgihdhk/temp/project_1.srcs/sources_1/bd/design_1/ip/design_1_m00_regslice_4/design_1_m00_regslice_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_m00_regslice_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
