#
# This workflow will compile the code and report compiling errors
#
name: C CI
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: sudo apt-get -y install rdma-core libibverbs1 libibverbs-dev
    - name: make_host
      run: cd host && make
